# Generated by Django 4.2.14 on 2024-07-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otp',
            table='otps',
        ),
    ]
