# Generated by Django 4.2.14 on 2024-07-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_options_usersuggestiontopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersuggestiontopic',
            name='topic',
            field=models.JSONField(default=list),
        ),
    ]
