# Generated by Django 4.2.14 on 2024-07-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_is_two_factor_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
