# Generated by Django 4.2.14 on 2024-07-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_secret_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
